
TORM = unit-test unit-test.o
CC = g++
CCFLAGS = -g -O3 -Wall -Wpointer-arith -Wcast-qual -Wwrite-strings
SOURCE_CODE_DIR = "../src/"

unit-test.o:
	cd ${SOURCE_CODE_DIR} ; make main.o
	
clean:
	rm -f ${TORM} 
